[package]
name = "enum-slicer-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.71", features = ["full"]}
quote = "1.0.36"
proc-macro2 = "1.0.86"
enum-slicer = { path = "../enum-slicer" }