[package]
name = "dependency_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.64"
rayon = "1.10.0"
criterion = "0.5.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
